x-logging: &default-logging
  driver: 'json-file'
  options:
    max-file: '5'
    max-size: '150m'

networks:
  docker_consul:
    external: true
  docker_backend:
    external: true

services:
  # Prometheus --------------------------------------------------------------------
  prometheus-vm-dev:
    container_name: prometheus-vm-dev
    image: prom/prometheus:v2.45.0
    networks:
      - docker_backend
    ports:
      - '9090:9090'
    volumes:
      - './prometheus:/usr/local/prometheus'
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    logging: *default-logging

  # Grafana --------------------------------------------------------------------
  grafana-vm-dev:
    container_name: grafana-vm-dev
    build:
      context: ./
      dockerfile: grafana/Dockerfile.grafana
    networks:
      - docker_backend
    depends_on:
      - prometheus-vm-dev
    ports:
      - '3000:3000'
    volumes:
      - './grafana:/usr/local/grafana'
    logging: *default-logging
