filebeat.inputs:
  - type: log
    id: log
    paths:
      - /usr/share/filebeat/ingest_data/*.log

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "/usr/share/filebeat/certs/ca/ca.crt"
