{
 "title": "Game Stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "gkey",
    "query": "{__name__=~\"sysstats_.*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Connect Users",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysstats_gauge_[[gkey]]_GameStats_CCU",
     "legendFormat": "CCU"
    }
   ]
  },
  {
   "title": "Daily Users",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysstats_counter_[[gkey]]_GameStats_Player_New",
     "legendFormat": "New"
    },
    {
     "expr": "sysstats_counter_[[gkey]]_GameStats_Player_Return",
     "legendFormat": "Returning"
    },
    {
     "expr": "sysstats_counter_[[gkey]]_GameStats_Player_New + sysstats_counter_[[gkey]]_GameStats_Player_Return",
     "legendFormat": "DAU"
    }
   ]
  },
  {
   "title": "Returning Users %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sysstats_counter_[[gkey]]_GameStats_Player_Return / (sysstats_counter_[[gkey]]_GameStats_Player_Return + sysstats_counter_[[gkey]]_GameStats_Player_New)) * 100"
    }
   ]
  },
  {
   "title": "Daily Revenue",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysstats_counter_[[gkey]]_GameStats_Daily_Revenue",
     "legendFormat": "revenue"
    }
   ]
  },
  {
   "title": "Number of Paying Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sysstats_counter_[[gkey]]_GameStats_Paying_Player"
    }
   ]
  },
  {
   "title": "Average Revenue Per User",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sysstats_counter_[[gkey]]_GameStats_Daily_Revenue /( sysstats_counter_[[gkey]]_GameStats_Player_New + sysstats_counter_[[gkey]]_GameStats_Player_Return)"
    }
   ]
  },
  {
   "title": "New Users %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sysstats_counter_[[gkey]]_GameStats_Player_New / (sysstats_counter_[[gkey]]_GameStats_Player_New + sysstats_counter_[[gkey]]_GameStats_Player_Return)) * 100"
    }
   ]
  },
  {
   "title": "Average Revenue Per Paying User",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sysstats_counter_[[gkey]]_GameStats_Daily_Revenue / sysstats_counter_[[gkey]]_GameStats_Paying_Player"
    }
   ]
  },
  {
   "title": "Monthly Active Users",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysstats_gauge_[[gkey]]_GameStats_MAU",
     "legendFormat": "MAU"
    }
   ]
  },
  {
   "title": "Monthly Revenue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysstats_gauge_[[gkey]]_GameStats_Monthly_Revenue",
     "legendFormat": "Revenue"
    }
   ]
  }
 ]
}