{
 "title": "Sys Stats",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gkey",
    "query": "{__name__=~\"sysstats_.*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Player",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Player onCommand",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_player_onCommand * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Player onRequest",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_player_onRequest * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Player onMessage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_player_onMessage * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Player onNotify",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_player_onNotify * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Player onEvent",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_player_onEvent * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Player onAction",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_player_onAction * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Game",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Game onCommand",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_game_onCommand * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Game onRequest",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_game_onRequest * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Game onMessage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_game_onMessage * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Game onNotify",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_game_onNotify * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Game onEvent",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_player_onEvent * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Game onAction",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_game_onAction * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Area",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Area onCommand",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_area_onCommand * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Area onRequest",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_area_onRequest * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Area onMessage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_area_onCommand * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Area onNotify",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_area_onNotify * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Area onEvent",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_area_onEvent * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Area onAction",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_area_onAction * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Group",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Group onCommand",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_group_onCommand * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Group onRequest",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_group_onRequest * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Group onMessage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_group_onNotify * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Group onNotify",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_group_onNotify * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Group onEvent",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_group_onEvent * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Group onAction",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "sysstats_gauge_[[gkey]]_group_onAction * 0.001",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  }
 ]
}